#!/usr/bin/env php
<?php
// ticket

use Symfony\Component\Console\Application;

### SETUP #############

require __DIR__ . '/vendor/autoload.php';

date_default_timezone_set('UTC');
setlocale(LC_ALL, 'en_GB.utf8', 'en_US.utf8', 'C.UTF-8');

### FUNCTIONS #########

function db( $filename )
{
    $dsn = 'sqlite:' . __DIR__ . DIRECTORY_SEPARATOR . $filename;
    $pdo = new PDO( $dsn, null, null, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_EMULATE_PREPARES => false, // seems unsupported in SQLite
    ] );

    return $pdo;
}

function addCmd( Application $app, PDO $db, array $commands )
{
    foreach ( $commands as $class ) {
        $class = 'TicketReader\\' . $class;
        $cmd = new $class( $pdo );
        $app->add( $cmd );
    }
}

### SCRIPT ############

$app = new Application( 'ARIN Ticket Reader', '0.1' );

addCmd( $app, db( 'tickets.sqlite' ), [
    'ApiKey',
] );

$app->run();
